using System.Text;

using NiveraAPI.Random.Engines;
using NiveraAPI.Utilities;

namespace NiveraAPI.Random;

/// <summary>
/// Provides functionality for generating random data including numbers, strings, and lists.
/// This class uses an instance of <see cref="IRandomGenerationEngine"/> to handle the core
/// random generation logic and provides a range of methods for generating different types of random values.
/// </summary>
public class RandomGeneration
{
	private readonly IRandomGenerationEngine _randomGenerationEngine;

	/// <summary>
	/// Gets the default instance of the <see cref="RandomGeneration"/> class.
	/// This instance uses the <see cref="DefaultGenerationEngine"/> to provide the
	/// random generation functionality.
	/// </summary>
	public static RandomGeneration Default { get; } = new(Singleton<DefaultGenerationEngine>.Value);

	/// <summary>
	/// Initializes a new instance of the <see cref="RandomGeneration"/> class.
	/// </summary>
	public RandomGeneration(IRandomGenerationEngine randomGenerationEngine)
	{
		_randomGenerationEngine = randomGenerationEngine;
	}

	/// <summary>
	/// Generates a random integer within a specified range.
	/// </summary>
	/// <param name="minValue">The inclusive lower bound of the random number.</param>
	/// <param name="maxValue">The exclusive upper bound of the random number.</param>
	/// <returns>A random integer within the specified range.</returns>
	public virtual int GetRandom(int minValue, int maxValue)
	{
		return _randomGenerationEngine.GetRandomValue(minValue, maxValue);
	}

	/// <summary>
	/// Generates a random floating-point number within a specified range.
	/// </summary>
	/// <param name="minValue">The inclusive lower bound of the random number.</param>
	/// <param name="maxValue">The exclusive upper bound of the random number.</param>
	/// <returns>A random floating-point number within the specified range.</returns>
	public virtual float GetRandom(float minValue, float maxValue)
	{
		return _randomGenerationEngine.GetRandomValue(minValue, maxValue);
	}

	/// <summary>
	/// Generates a random byte value within the specified range.
	/// </summary>
	/// <param name="minValue">The inclusive lower bound of the random byte to generate.</param>
	/// <param name="maxValue">The exclusive upper bound of the random byte to generate.</param>
	/// <returns>A random byte value greater than or equal to <paramref name="minValue"/> and less than <paramref name="maxValue"/>.</returns>
	public virtual byte GetRandom(byte minValue, byte maxValue)
	{
		return _randomGenerationEngine.GetRandomValue(minValue, maxValue);
	}

	/// <summary>
	/// Generates a random boolean value.
	/// </summary>
	/// <returns>A randomly generated boolean value.</returns>
	public virtual bool GetBool()
	{
		return GetRandom(0, 1) == 1;
	}

	/// <summary>
	/// Generates a readable string of the specified length using a random sequence of characters.
	/// </summary>
	/// <param name="length">The desired length of the generated string.</param>
	/// <returns>A readable string of the specified length.</returns>
	public virtual string GetReadableString(int length)
	{
		return Convert.ToBase64String(GenerateBytes(length).ToArray()).TrimEnd(new char[1] { '=' }).Substring(0, length);
	}

	/// <summary>
	/// Generates a random string with a specified length.
	/// </summary>
	/// <param name="length">The desired length of the generated string.</param>
	/// <param name="finishString">An optional callback action to perform additional operations on the generated string.</param>
	/// <returns>A randomly generated string of the specified length.</returns>
	public virtual string GetString(int length, Action<string>? finishString = null)
	{
		var text = "";

		for (var i = 0; i < length; i++)
		{
			var random = GetRandom((byte)0, byte.MaxValue);
			var @string = Encoding.UTF8.GetString(new byte[1] { random }, 0, 1);
			
			text += @string;
		}
		
		finishString?.Invoke(text);
		return text;
	}

	/// <summary>
	/// Generates a sequence of random bytes based on the specified parameters.
	/// </summary>
	/// <param name="minElementSize">The minimum value for each byte in the generated sequence.</param>
	/// <param name="maxElementSize">The maximum value for each byte in the generated sequence.</param>
	/// <param name="size">The number of random bytes to generate. Defaults to 255.</param>
	/// <param name="mode">The mode of generation, determining if duplicates are allowed or not.</param>
	/// <returns>A collection of randomly generated bytes.</returns>
	public virtual List<byte> GenerateBytes(byte minElementSize, byte maxElementSize, int size = 255, RandomListGenerationMode mode = RandomListGenerationMode.AllowMultiple)
	{
		if (size > byte.MaxValue && mode is RandomListGenerationMode.SingleOccurence)
			throw new ArgumentOutOfRangeException(nameof(size), "Size cannot be greater than 255 when mode is SingleOccurence.");
		
		var list = new List<byte>(size);
		
		for (var i = 0; i < size; i++)
		{
			if (mode == RandomListGenerationMode.AllowMultiple)
			{
				list.Add(GetRandom(minElementSize, maxElementSize));
				continue;
			}
			
			var random = GetRandom(minElementSize, maxElementSize);
			
			while (list.Contains(random))
				random = GetRandom(minElementSize, maxElementSize);
			
			list.Add(random);
		}
		
		return list;
	}

	/// <summary>
	/// Generates a list of random integers within the specified range.
	/// </summary>
	/// <param name="minElementSize">The minimum value (inclusive) for the generated integers.</param>
	/// <param name="maxElementSize">The maximum value (exclusive) for the generated integers.</param>
	/// <param name="size">The number of integers to generate. Defaults to 255.</param>
	/// <param name="mode">The generation mode determining whether duplicates are allowed or not.</param>
	/// <returns>A list of randomly generated integers adhering to the specified parameters.</returns>
	public virtual List<int> GenerateValues(int minElementSize, int maxElementSize, int size = 255,
		RandomListGenerationMode mode = RandomListGenerationMode.AllowMultiple)
	{
		var list = new List<int>(size);

		for (var i = 0; i < size; i++)
		{
			if (mode == RandomListGenerationMode.AllowMultiple)
			{
				list.Add(GetRandom(minElementSize, maxElementSize));
				continue;
			}
			
			var random = GetRandom(minElementSize, maxElementSize);
			
			while (list.Contains(random))
				random = GetRandom(minElementSize, maxElementSize);
			
			list.Add(random);
		}
		
		return list;
	}

	/// <summary>
	/// Generates a sequence of random bytes using the default range of values.
	/// </summary>
	/// <param name="size">The number of random bytes to generate. Defaults to 255.</param>
	/// <param name="mode">The mode of generation, determining if duplicates are allowed or not.</param>
	/// <returns>A collection of randomly generated bytes.</returns>
	public virtual List<byte> GenerateBytes(int size = 255,
		RandomListGenerationMode mode = RandomListGenerationMode.AllowMultiple)
	{
		return GenerateBytes(0, byte.MaxValue, size, mode);
	}

	/// <summary>
	/// Generates a list of random integers within the specified range.
	/// </summary>
	/// <param name="minElementSize">The minimum value (inclusive) for the generated integers.</param>
	/// <param name="maxElementSize">The maximum value (exclusive) for the generated integers.</param>
	/// <param name="size">The number of integers to generate. Defaults to 255.</param>
	/// <param name="mode">The generation mode determining whether duplicates are allowed or not.</param>
	/// <returns>A list of randomly generated integers adhering to the specified parameters.</returns>
	public virtual List<int> GenerateValues(int size = 255,
		RandomListGenerationMode mode = RandomListGenerationMode.AllowMultiple)
	{
		return GenerateValues(0, 255, size, mode);
	}

	/// <summary>
	/// Restores the order of elements in a collection based on a specified order sequence.
	/// </summary>
	/// <typeparam name="TElement">The type of elements in the collection.</typeparam>
	/// <param name="collection">The collection of elements whose order is to be restored.</param>
	/// <param name="order">The sequence of indices representing the desired order.</param>
	public virtual void RestoreOrder<TElement>(IList<TElement> collection, IEnumerable<int> order)
	{
		for (var i = 0; i < collection.Count; i++)
		{
			collection[i] = collection[order.ElementAtOrDefault(i)];
		}
	}

	/// <summary>
	/// Randomizes the order of elements in the specified collection and saves the resulting order indices.
	/// </summary>
	/// <typeparam name="TElement">The type of elements in the collection.</typeparam>
	/// <param name="collection">The collection of elements to randomize.</param>
	/// <returns>An array of integers representing the new order of elements in the collection.</returns>
	public virtual int[] RandomOrderSave<TElement>(IList<TElement> collection)
	{
		var array = new int[collection.Count];
		var array2 = GenerateValues(0, collection.Count, collection.Count, RandomListGenerationMode.SingleOccurence).ToArray();
		
		for (var i = 0; i < collection.Count; i++)
		{
			array[i] = array2[i];
			collection[i] = collection[array2[i]];
		}
		
		return array;
	}
}